version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./backend
    command: celery -A birthday_invite_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - backend
